config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin, path: Spree.admin_path do
    resources :banners
  end
end

app/models/overrides/spree/layouts/add_banner_text.rb
Deface::Override.new(
  virtual_path: 'spree/layouts/spree_application',
  name: 'add banner text',
  insert_top: "[data-hook='body']",
  text: "
  <h5 class='text-center'><%= current_store.banner_text%></h5>
")

app/models/spree/banner.rb
# frozen_string_literal: true

module Spree
  class Banner < ApplicationRecord
    include ActiveModel::Dirty
    validates :content, presence: true
    validates :name, presence: true
    belongs_to :store

    before_save :set_banner, if: :published_changed?

    def set_banner
      Spree::Banner.where(store_id: store_id).update_all(published: false)
    end
  end
end

app/models/spree/store_decorator.rb
module Spree
  module StoreDecorator
    def self.prepended(base)
      base.has_many :banners
    end
  end
end

Spree::Store.prepend Spree::StoreDecorator

app/models/spree_store_banner/configuration.rb
# frozen_string_literal: true

module SpreeStoreBanner
  class Configuration < Spree::Preferences::Configuration
    # Some example preferences are shown below, for more information visit:
    # https://dev-docs.spreecommerce.org/internals/preferences

    preference :enabled, :boolean, default: true
    # preference :dark_chocolate, :boolean, default: true
    # preference :color, :string, default: 'Red'
    # preference :favorite_number, :integer
    # preference :supported_locales, :array, default: [:en]
  end
end

app/models/spree_store_banner/store_decorator.rb
module SpreeStoreBanner
  module StoreDecorator
    def self.prepended(base)
      base.has_many :banners
    end
  end
end

Spree::Store.prepend SpreeStoreBanner::StoreDecorator

app/controllers/spree/admin/banners_controller.rb
module Spree
  module Admin
    class BannersController < ResourceController
      def index
        @banners = current_store.banners
      end
    end
  end
end

app/helpers/spree/base_helper_decorator.rb
module Spree
  module BaseHelperDecorator
    def banner
      banners = current_store.banners.where(published: true)
      banners.each do |banner|
        @result = banner
      end
      @result
    end
  end
end

::Spree::BaseHelper.prepend ::Spree::BaseHelperDecorator

app/helpers/spree_store_banner/frontend_helper_decorator.rb
module SpreeStoreBanner
  module FrontendHelperDecorator
    def banner
      return unless current_store.present?

      banners = current_store.banners.where(published: true)
      banners.each do |banner|
        @result = banner
      end

      @result
    end
  end
end

Spree::FrontendHelper.prepend(SpreeStoreBanner::FrontendHelperDecorator)

app/views/spree/admin/banners/_form.html.erb
<div class='card mb-4'>
  <div class='card-header'>
    <h1 class='card-title mb-0 h5'>
      <%= Spree.t(:banner) %>
    </h1>
  </div>
  <div class='card-body'>
    <div class='text-center col-12'>
      <%= Spree.t('store_form.If you want to link your banner in index page') %>
    </div>
    <div class="row align-items-center">
      <div class="col-12">
        <%= f.field_container :name do %>
          <%= f.label :banner, Spree.t(:banner_name) %><span class="required font-weight-bold text-danger">*</span>
          <%= f.error_message_on :name %>
          <%= f.text_field :name, class: 'form-control' ,required: true%>
        <% end %>
      </div>
      <div class="col-6">
        <%= f.field_container :color do %>
          <%= f.label :banner, Spree.t(:banner_color) %> <br>
          <%= f.color_field :color, class: 'form-control' %>
          <%= f.error_message_on :color %>
        <% end %>
      </div>
      <div class="col-6">
        <%= f.field_container :published do %>
          <div class='text-center'>
            <%= f.check_box :published, class: 'form-check-input'%>
            <%= f.label :banner, Spree.t(:published), class:'form-check-label' %>
            <%= f.error_message_on :published %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <%= f.field_container :content do %>
          <%= f.label :banner, Spree.t(:banner_content) %><span class="required font-weight-bold text-danger">*</span>
          <%= f.error_message_on :content %>
          <%= f.text_area :content, class: 'form-control spree-rte'%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/banners/edit.html.erb
<% content_for :page_title do %>
  <div class="d-flex pt-2">
    <%= link_to Spree.t(:banners), spree.admin_banners_url %>/
    <%= @banner.name %>
  </div>
<% end %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @banner } %>
<%= form_for [:admin, @banner] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: spree.admin_banners_path } %>
  </fieldset>
<% end %>

app/views/spree/admin/banners/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:banners) %>
<% end %>
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_banner), new_admin_banner_url, class: "btn btn-primary", icon: 'add.svg', id: 'admin_new_role_link' %>
<% end if can? :create, Spree::Banner %>
<% if @banners.any? %>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:color) %></th>
        <th><%= Spree.t(:published) %></th>
        <th data-hook="admin_stores_index_header_actions" class="actions"></th>
      <thead>
      <tbody>
        <% @banners.each do |banner| %>
        <tr>
          <td><%= banner.name %></td>
          <td><%= banner.color %></td>
          <td><%= banner.published%></td>
          <td class="actions" data-hook="admin_stores_index_row_actions">
            <span class="d-flex justify-content-end">
            <%= link_to_edit_url spree.edit_admin_banner_path(banner), no_text: true if can?(:edit, banner) %>
            <%= link_to_delete banner, no_text: true, url: spree.admin_banner_path(banner) if can?(:destroy, banner) %>
            </span>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Banner)) %>,
    <%= link_to(Spree.t(:add_one), new_admin_banner_url) if can? :create, Spree::Banner %>!
  </div>
<% end %>

app/views/spree/admin/banners/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:banner), spree.admin_banners_url %> /
  <%= Spree.t(:new_banner) %>
<% end %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @banner } %>
<%= form_for [:admin, @banner] , url: spree.admin_banners_path  do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links', locals: { collection_url: spree.admin_banners_path(@banner) } %>
  </fieldset>
<% end %>

app/views/spree/shared/_banner.html.erb
<style>
  #banner {
  background: <%= banner&.color %>;
  }
</style>
<div id="banner" class="d-flex justify-content-center align-items-center">
  <div class="row">
    <div class="col-12 text-center">
        <%= banner&.content&.html_safe %>
    </div>
  </div>
</div>

app/views/spree/shared/_header.html.erb
<%# leaving #spree-header div for legacy support  %>
<% cache spree_nav_cache_key("#{banner.present? ? "#{banner.updated_at.to_i}_header" : 'header'}") do %>
  <div id="spree-header" class="<%= 'mb-5' if banner.present? %> ">
    <header id="header" class="d-flex align-items-center header-spree border-bottom <%= 'mt-5' if banner.present? %>">
      <div class="container-fluid h-100 header-spree-fluid">
        <div class="d-flex flex-nowrap align-items-center h-100 px-2">
          <div class="d-xl-none flex-grow-1 header-spree-fluid-mobile-menu-toggler">
            <button class="navbar-toggler border-0 px-0 d-flex" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-label="<%= Spree.t('nav_bar.show_menu') %>">
              <%= icon(name: 'burger',
                      width: 18.5,
                      height: 16) %>
            </button>
          </div>
          <figure class="logo flex-grow-0 flex-xl-grow-1 order-xl-0 header-spree-fluid-logo m-0">
            <%= logo %>
          </figure>
          <div id="main-nav-bar" class="flex-grow-0 d-none d-xl-block h-100 header-spree-fluid-primary-navigation">
            <%= render partial: 'spree/shared/main_nav_bar' %>
            <%= render partial: 'spree/shared/banner' %>
          </div>
          <div id="top-nav-bar" class="flex-grow-1 header-spree-fluid-secondary-navigation">
            <%= render partial: 'spree/shared/nav_bar' %>
            <%= render partial: 'spree/shared/banner' %>
          </div>
          <%= render partial: 'spree/shared/mobile_navigation' %>
        </div>
      </div>
    </header>
  </div>
<% end %>